server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstare?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    com.webstare.backend: debug
